[package]
name = "ixaccess-py"
version = "0.1.0"
edition = "2021"

[lib]
name = "ixaccess"
crate-type = ["cdylib"]

[dependencies]
ixaccess = { path = "../../rs/ixaccess" }
pyo3 = { version = "0.27", features = ["extension-module"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
