[package]
name = 'ixaccess-r'
publish = false
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'ixaccess'

[dependencies]
extendr-api = '0.8.1'
ixaccess = { path = "../../../../rs/ixaccess", features = ["extendr-api"] }
tokio = { version = "1", features = ["rt-multi-thread"] }

[profile.release]
lto = true
codegen-units = 1
