# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_ixaccess_wrappers", use_symbols = TRUE, package_name = "ixaccess")

#' @usage NULL
#' @useDynLib ixaccess, .registration = TRUE
NULL

IxAccessClientInternal <- new.env(parent = emptyenv())

IxAccessClientInternal$new <- function(path) .Call(wrap__IxAccessClientInternal__new, path)

IxAccessClientInternal$list_roles <- function() .Call(wrap__IxAccessClientInternal__list_roles, self)

IxAccessClientInternal$list_all_roles_for_role <- function(role) .Call(wrap__IxAccessClientInternal__list_all_roles_for_role, self, role)

IxAccessClientInternal$add_role <- function(role) .Call(wrap__IxAccessClientInternal__add_role, self, role)

IxAccessClientInternal$add_roles <- function(roles) .Call(wrap__IxAccessClientInternal__add_roles, self, roles)

IxAccessClientInternal$assign_role <- function(assignee, role) .Call(wrap__IxAccessClientInternal__assign_role, self, assignee, role)

IxAccessClientInternal$assign_resource_to_role <- function(role, resource_tag, resource_value) .Call(wrap__IxAccessClientInternal__assign_resource_to_role, self, role, resource_tag, resource_value)

IxAccessClientInternal$get_all_resources_for_role_by_tag <- function(role, tag) .Call(wrap__IxAccessClientInternal__get_all_resources_for_role_by_tag, self, role, tag)

IxAccessClientInternal$unassign_role <- function(assignee, role) .Call(wrap__IxAccessClientInternal__unassign_role, self, assignee, role)

IxAccessClientInternal$unassign_resource_from_role <- function(role, resource_tag, resource_value) .Call(wrap__IxAccessClientInternal__unassign_resource_from_role, self, role, resource_tag, resource_value)

#' @export
`$.IxAccessClientInternal` <- function (self, name) { func <- IxAccessClientInternal[[name]]; environment(func) <- environment(); func }

#' @export
`[[.IxAccessClientInternal` <- `$.IxAccessClientInternal`


# nolint end
