name: Test Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust 1.85
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.85
          profile: minimal
          override: true

      - name: Run cargo test
        run: cargo test --verbose --package ixaccess
